### ISSUE TITLE
BUG: Setup Wizard not installed. 

### ISSUE THREAD

**Issue by MaxPh1107** [rhino-linux/rhino-setup#57] opened 2023-08-30 18:25 UTC
**Rhino Linux Version:**
A numerical version for Rhino Linux. 
2023.2(mainline) x86_64

**Platform:**
[CPU: Intel Pentium N3700 (4) @ 2.400GHz / Compaq Pressario 420 - N14JP6-V2]

![IMG_20230830_152351_494.jpg](https://github.com/rhino-linux/rhino-setup/assets/123606054/cc417da0-282c-4876-b1a1-1c803abc2b3c)

**Comment by Elsie19** [comment] 2023-08-31 01:00
Run `rhino-setup`, and if that doesn't work, run `pacstall -I rhino-setup-bin`.

**Comment by ajstrongdev** [comment] 2023-09-09 11:18
@Elsie19 Did this occur for you?

**Comment by Elsie19** [comment] 2023-09-09 12:36
No

**Comment by ajstrongdev** [comment] 2023-09-10 09:25
Closing this as can't reproduce as tests on both x86_64 and ARM64 devices have not had this issue occur.

**Closed** 2023-09-10 09:25 UTC
